#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Ana Elissa Cabrera

# Short bio or description (displayed in the header)
description: I recently graduated the Univeristy of Illinois at Urbana-Champaign during the pandemic. 
I studied Political Science and Linguistics in undergrad but I always had an instrinsic curiosity
toward Computer Science since I was a little girl. I wanted to challenge my intellectual capability in
engineering and decided to go back to school for the Illinois Computing Accelerator for Non-Specialists (iCAN) program
that UIUC offered for college graduates witho non-CS degrees interested in switching their life careers.
I am completing my last semester of the iCAN program this Summer 2022, where I am researching topics in
robotics and motion planning at the Parasol Lab. I am also taking a 400-level CS class at my university
and working a second job. On my free time, I like to dance, draw, play the piano, swim laps, and write.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/aec4.jpg

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: aec4@illinois.edu
  facebook:
  linkedin:
  rss: # just type anything here for a working RSS icon

# Your website URL (e.g. http://ajstent.github.io)
# Used for Sitemap.xml and your RSS feed
url: http://cabreraleon.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/



# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

theme: jekyll-theme-cayman
